apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-metrics
  namespace: nginx-ingress
  labels:
    app.kubernetes.io/name: nginx-ingress
    app.kubernetes.io/component: controller
    app.kubernetes.io/part-of: cloud-native-inventory-platform
spec:
  type: ClusterIP
  selector:
    app: nginx-ingress
  ports:
    - name: metrics
      port: 9113
      targetPort: 9113
      protocol: TCP
