workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "trigger"'
    - when: never

stages:
  - test
  - build

backend-test:
  stage: test
  tags:
    - inventory-runner
  image: 192.168.122.1:8083/python:3.14
  services:
    - name: 192.168.122.1:8083/postgres:16
      alias: postgres
  variables:
    POSTGRES_DB: inventory-test
    POSTGRES_USER: inventory_user
    POSTGRES_PASSWORD: inventory_password

    DB_NAME: inventory-test
    DB_USER: inventory_user
    DB_PASSWORD: inventory_password
    DB_HOST: postgres
    DB_PORT: 5432
  script:
    - echo "Running backend tests inside Docker"
    - cd application/backend
    - python --version
    - pip install -r requirements.txt
    - python manage.py check
    - python manage.py test

backend-build:
  stage: build
  tags:
    - inventory-runner
  image: 192.168.122.1:8083/docker:latest
  script:
    - echo "Building Docker image"
    - docker build -t inventory-backend:$CI_COMMIT_SHORT_SHA application/backend
    - echo "Login to Nexus registry"
    - echo "$NEXUS_PASSWORD" | docker login -u "$NEXUS_USERNAME" --password-stdin "$NEXUS_REGISTRY"
    - echo "Tagging image"
    - docker tag inventory-backend:$CI_COMMIT_SHORT_SHA $NEXUS_REGISTRY/inventory/backend:$CI_COMMIT_SHORT_SHA
    - docker tag inventory-backend:$CI_COMMIT_SHORT_SHA $NEXUS_REGISTRY/inventory/backend:latest
    - echo "Pushing image"
    - docker push $NEXUS_REGISTRY/inventory/backend:$CI_COMMIT_SHORT_SHA
    - docker push $NEXUS_REGISTRY/inventory/backend:latest