apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: inventory
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/part-of: cloud-native-inventory-platform
data:
  DB_NAME: inventory
  DB_HOST: postgres
  DB_PORT: "5432"
  ALLOWED_HOSTS: "inventory.local,localhost,127.0.0.1"
  CELERY_BROKER_URL: "redis://redis:6379/0"
  CELERY_RESULT_BACKEND: "redis://redis:6379/1"
  DEBUG: "False"
  SECURE_SSL_REDIRECT: "False"
  SESSION_COOKIE_SECURE: "False"
  CSRF_COOKIE_SECURE: "False"
  SECURE_HSTS_SECONDS: "0"
  SECURE_HSTS_INCLUDE_SUBDOMAINS: "False"
  SECURE_HSTS_PRELOAD: "False"
  TRUST_X_FORWARDED_PROTO: "False"
