apiVersion: v1
kind: Namespace
metadata:
  name: gitlab-agent-inventory-lab

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab-deployer
  namespace: gitlab-agent-inventory-lab
  labels:
    app.kubernetes.io/part-of: cloud-native-inventory-platform

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gitlab-agent-leader-election
  namespace: gitlab-agent-inventory-lab
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gitlab-agent-leader-election
  namespace: gitlab-agent-inventory-lab
subjects:
  - kind: ServiceAccount
    name: gitlab-deployer
    namespace: gitlab-agent-inventory-lab
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gitlab-agent-leader-election

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gitlab-deployer
  namespace: inventory
rules:
  # GitLab CD can update backend/frontend images
  # and watch Deployment rollout status.
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch
      - patch
  # GitLab CD can create and monitor migration Jobs.
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - get
      - list
      - watch
      - create
  # Useful for observing migration Pods and reading logs
  # when a deployment fails.
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods/log
    verbs:
      - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gitlab-deployer
  namespace: inventory
subjects:
  - kind: ServiceAccount
    name: gitlab-deployer
    namespace: gitlab-agent-inventory-lab
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gitlab-deployer