apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  namespace: inventory
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/part-of: cloud-native-inventory-platform

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-sa
  namespace: inventory
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/part-of: cloud-native-inventory-platform

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: migration-sa
  namespace: inventory
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/component: migration
    app.kubernetes.io/part-of: cloud-native-inventory-platform

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: celery-sa
  namespace: inventory
  labels:
    app.kubernetes.io/name: celery
    app.kubernetes.io/component: worker
    app.kubernetes.io/part-of: cloud-native-inventory-platform