# Generated by Django 5.2.17 on 2026-09-06 08:55

import inventory.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/', validators=[inventory.validators.validate_product_image]),
        ),
    ]
