# Generated by Django 5.2.17 on 2026-09-07 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_inventorymovement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], max_length=20, null=True)),
                ('to_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_history', to='inventory.order')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_status_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at', 'id'),
                'indexes': [models.Index(fields=['order', 'created_at'], name='inventory_o_order_i_eba918_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('from_status__isnull', True), ('from_status__in', ['pending', 'processing', 'shipped', 'delivered', 'cancelled']), _connector='OR'), name='order_history_from_status_valid'), models.CheckConstraint(condition=models.Q(('to_status__in', ['pending', 'processing', 'shipped', 'delivered', 'cancelled'])), name='order_history_to_status_valid'), models.CheckConstraint(condition=models.Q(('from_status__isnull', True), models.Q(('from_status', models.F('to_status')), _negated=True), _connector='OR'), name='order_history_statuses_differ')],
            },
        ),
    ]
