# Generated by Django 5.2.17 on 2026-09-07 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_orderstatushistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('user.created', 'User created'), ('user.registered', 'User registered'), ('user.activated', 'User activated'), ('user.deactivated', 'User deactivated'), ('user.role_changed', 'User role changed'), ('user.password_changed', 'User password changed'), ('product.created', 'Product created'), ('product.updated', 'Product updated'), ('product.activated', 'Product activated'), ('product.deactivated', 'Product deactivated'), ('product.deleted', 'Product deleted'), ('warehouse.created', 'Warehouse created'), ('warehouse.updated', 'Warehouse updated'), ('warehouse.deleted', 'Warehouse deleted'), ('inventory.created', 'Inventory created'), ('inventory.adjusted', 'Inventory adjusted'), ('inventory.deleted', 'Inventory deleted'), ('order.created', 'Order created'), ('order.status_changed', 'Order status changed'), ('payment.succeeded', 'Payment succeeded')], max_length=40)),
                ('target_type', models.CharField(choices=[('user', 'User'), ('product', 'Product'), ('warehouse', 'Warehouse'), ('inventory', 'Inventory'), ('order', 'Order'), ('payment', 'Payment')], max_length=20)),
                ('target_id', models.CharField(max_length=100)),
                ('target_label', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['created_at'], name='inventory_a_created_1da8ce_idx'), models.Index(fields=['action', 'created_at'], name='inventory_a_action_2faaed_idx'), models.Index(fields=['target_type', 'target_id', 'created_at'], name='inventory_a_target__e8db0a_idx')],
            },
        ),
    ]
