name: Trigger GitLab CI Pipeline

on:
  push:
    branches:
      - main

concurrency:
  group: gitlab-trigger-main
  cancel-in-progress: true

jobs:
  trigger-gitlab:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitLab Pipeline
        run: |
          curl --fail \
          -F token=${{ secrets.GITLAB_TRIGGER_TOKEN }} \
          -F ref=main \
          https://hamgit.ir/api/v4/projects/48015/trigger/pipeline